services:
  - type: web
    name: hjv-leadership-app-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 10